version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: italocedro
      POSTGRES_PASSWORD: db1010
      POSTGRES_DB: spring-api
    ports:
      - "5432:5432"